export const properties = [
  {
    id: 1,
    title: "100 Broadview Avenue, 400, Toronto, ON",
    address: "100 Broadview Avenue, Toronto, ON",
    fullAddress: "100 Broadview Avenue, Old Toronto, ON, M4M 3H3",
    price: "$39.5 SF/Yr",
    image: "/place-holder.webp",
    status: "FOR LEASE",
    type: "OFFICE",
    latitude: 43.6573,
    longitude: -79.3487,
    details: [{ label: "Building Size", value: "10,000 Sf" }],
  },
  {
    id: 2,
    title: "2305 W Altorfer Drive",
    address: "2305 W Altorfer Drive, Peoria, IL, 61615",
    price: "$760,000",
    image: "/place-holder.webp",
    status: "FOR SALE",
    type: "INDUSTRIAL",
    latitude: 40.7654,
    longitude: -89.6393,
    details: [
      { label: "Year Built", value: "1985" },
      { label: "Land Size", value: "1.25 Ac" },
      { label: "Building Size", value: "11,400 Sf" },
    ],
  },
  {
    id: 3,
    title: "500 Main Street, Chicago",
    address: "500 Main Street, Chicago, IL",
    price: "$1,200,000",
    image: "/place-holder.webp",
    status: "FOR SALE",
    type: "COMMERCIAL",
    latitude: 41.8781,
    longitude: -87.6298,
    details: [
      { label: "Year Built", value: "2005" },
      { label: "Building Size", value: "15,000 Sf" },
    ],
  },
  {
    id: 4,
    title: "123 Market Avenue, San Francisco",
    address: "123 Market Avenue, San Francisco, CA",
    price: "$4,500,000",
    image: "/place-holder.webp",
    status: "FOR SALE",
    type: "RETAIL",
    latitude: 37.7749,
    longitude: -122.4194,
    details: [
      { label: "Year Built", value: "1998" },
      { label: "Building Size", value: "8,500 Sf" },
    ],
  },
  {
    id: 5,
    title: "789 Business Park, Dallas",
    address: "789 Business Park, Dallas, TX",
    price: "$55 SF/Yr",
    image: "/place-holder.webp",
    status: "FOR LEASE",
    type: "OFFICE",
    latitude: 32.7767,
    longitude: -96.797,
    details: [
      { label: "Year Built", value: "2015" },
      { label: "Building Size", value: "22,000 Sf" },
    ],
  },
  // Tambahkan properti di area yang sama untuk menguji clustering
  {
    id: 6,
    title: "456 Tech Avenue, San Francisco",
    address: "456 Tech Avenue, San Francisco, CA",
    price: "$3,200,000",
    image: "/place-holder.webp",
    status: "FOR SALE",
    type: "OFFICE",
    latitude: 37.7739,
    longitude: -122.4194,
    details: [
      { label: "Year Built", value: "2010" },
      { label: "Building Size", value: "12,000 Sf" },
    ],
  },
  {
    id: 7,
    title: "789 Startup Street, San Francisco",
    address: "789 Startup Street, San Francisco, CA",
    price: "$75 SF/Yr",
    image: "/place-holder.webp",
    status: "FOR LEASE",
    type: "OFFICE",
    latitude: 37.7729,
    longitude: -122.4194,
    details: [
      { label: "Year Built", value: "2018" },
      { label: "Building Size", value: "18,000 Sf" },
    ],
  },
  {
    id: 8,
    title: "101 Innovation Hub, San Francisco",
    address: "101 Innovation Hub, San Francisco, CA",
    price: "$5,800,000",
    image: "/place-holder.webp",
    status: "FOR SALE",
    type: "MIXED USE",
    latitude: 37.7719,
    longitude: -122.4184,
    details: [
      { label: "Year Built", value: "2020" },
      { label: "Building Size", value: "25,000 Sf" },
    ],
  },
  {
    id: 9,
    title: "222 Financial District, New York",
    address: "222 Financial District, New York, NY",
    price: "$12,500,000",
    image: "/place-holder.webp",
    status: "FOR SALE",
    type: "OFFICE",
    latitude: 40.7128,
    longitude: -74.006,
    details: [
      { label: "Year Built", value: "1995" },
      { label: "Building Size", value: "45,000 Sf" },
    ],
  },
  {
    id: 10,
    title: "333 Manhattan Avenue, New York",
    address: "333 Manhattan Avenue, New York, NY",
    price: "$95 SF/Yr",
    image: "/place-holder.webp",
    status: "FOR LEASE",
    type: "RETAIL",
    latitude: 40.7138,
    longitude: -74.005,
    details: [
      { label: "Year Built", value: "2005" },
      { label: "Building Size", value: "15,000 Sf" },
    ],
  },
  {
    id: 11,
    title: "444 Broadway Street, New York",
    address: "444 Broadway Street, New York, NY",
    price: "$8,900,000",
    image: "/place-holder.webp",
    status: "FOR SALE",
    type: "MIXED USE",
    latitude: 40.7148,
    longitude: -74.004,
    details: [
      { label: "Year Built", value: "1988" },
      { label: "Building Size", value: "30,000 Sf" },
    ],
  },
  {
    id: 12,
    title: "555 Downtown Loop, Chicago",
    address: "555 Downtown Loop, Chicago, IL",
    price: "$4,200,000",
    image: "/place-holder.webp",
    status: "FOR SALE",
    type: "COMMERCIAL",
    latitude: 41.8791,
    longitude: -87.6298,
    details: [
      { label: "Year Built", value: "2000" },
      { label: "Building Size", value: "18,000 Sf" },
    ],
  },
  {
    id: 13,
    title: "666 Lakefront Drive, Chicago",
    address: "666 Lakefront Drive, Chicago, IL",
    price: "$65 SF/Yr",
    image: "/place-holder.webp",
    status: "FOR LEASE",
    type: "OFFICE",
    latitude: 41.8771,
    longitude: -87.6288,
    details: [
      { label: "Year Built", value: "2012" },
      { label: "Building Size", value: "22,000 Sf" },
    ],
  },
  {
    id: 14,
    title: "777 Michigan Avenue, Chicago",
    address: "777 Michigan Avenue, Chicago, IL",
    price: "$5,500,000",
    image: "/place-holder.webp",
    status: "FOR SALE",
    type: "RETAIL",
    latitude: 41.8761,
    longitude: -87.6278,
    details: [
      { label: "Year Built", value: "1998" },
      { label: "Building Size", value: "14,000 Sf" },
    ],
  },
  {
    id: 15,
    title: "888 Rodeo Drive, Los Angeles",
    address: "888 Rodeo Drive, Los Angeles, CA",
    price: "$15,800,000",
    image: "/place-holder.webp",
    status: "FOR SALE",
    type: "RETAIL",
    latitude: 34.0522,
    longitude: -118.2437,
    details: [
      { label: "Year Built", value: "2008" },
      { label: "Building Size", value: "20,000 Sf" },
    ],
  },
  {
    id: 16,
    title: "999 Hollywood Blvd, Los Angeles",
    address: "999 Hollywood Blvd, Los Angeles, CA",
    price: "$120 SF/Yr",
    image: "/place-holder.webp",
    status: "FOR LEASE",
    type: "OFFICE",
    latitude: 34.0532,
    longitude: -118.2427,
    details: [
      { label: "Year Built", value: "2015" },
      { label: "Building Size", value: "35,000 Sf" },
    ],
  },
  {
    id: 17,
    title: "1010 Sunset Strip, Los Angeles",
    address: "1010 Sunset Strip, Los Angeles, CA",
    price: "$9,200,000",
    image: "/place-holder.webp",
    status: "FOR SALE",
    type: "MIXED USE",
    latitude: 34.0542,
    longitude: -118.2417,
    details: [
      { label: "Year Built", value: "2005" },
      { label: "Building Size", value: "28,000 Sf" },
    ],
  },
  {
    id: 18,
    title: "1111 Peachtree Street, Atlanta",
    address: "1111 Peachtree Street, Atlanta, GA",
    price: "$3,800,000",
    image: "/place-holder.webp",
    status: "FOR SALE",
    type: "OFFICE",
    latitude: 33.749,
    longitude: -84.388,
    details: [
      { label: "Year Built", value: "2002" },
      { label: "Building Size", value: "16,000 Sf" },
    ],
  },
  {
    id: 19,
    title: "1212 Downtown District, Atlanta",
    address: "1212 Downtown District, Atlanta, GA",
    price: "$45 SF/Yr",
    image: "/place-holder.webp",
    status: "FOR LEASE",
    type: "RETAIL",
    latitude: 33.75,
    longitude: -84.387,
    details: [
      { label: "Year Built", value: "2010" },
      { label: "Building Size", value: "12,000 Sf" },
    ],
  },
  {
    id: 20,
    title: "1313 Buckhead Avenue, Atlanta",
    address: "1313 Buckhead Avenue, Atlanta, GA",
    price: "$4,500,000",
    image: "/place-holder.webp",
    status: "FOR SALE",
    type: "COMMERCIAL",
    latitude: 33.751,
    longitude: -84.386,
    details: [
      { label: "Year Built", value: "2008" },
      { label: "Building Size", value: "20,000 Sf" },
    ],
  },
];
